### ISSUE TITLE
刷时长功能已失效

### ISSUE THREAD

**Issue by Alicil** [TwoOnefour/Sign_xy#4]
小雅刷时长部分，请求携带的json添加了nonce，signature，timestamp

**Comment by TwoOnefour** [comment]
> 小雅刷时长部分，请求携带的json添加了nonce，signature，timestamp

@Alicil 已更新

加密实现部分详见https://github.com/TwoOnefour/Sign_xy/commit/9fe1eb9eac3dd4ea28c7a44ec1806460b3920cb9

![屏幕截图 2024-11-29 170612](https://github.com/user-attachments/assets/9d3e43ff-8dc3-44fc-a2c8-a3b9333b6ba5)
